"""Seed demo profiles + analyses into the liai database."""
import json, sys
sys.path.insert(0, ".")
from linkedin_ai.database import Database
from linkedin_ai.utils import now_iso

db = Database("database/liai.db")

profiles = [
    {"url":"https://linkedin.com/in/sarah-chen-ml","name":"Sarah Chen","headline":"ML Platform Lead @ Stripe | Ex-Google Brain","company":"Stripe","title":"ML Platform Lead","location":"San Francisco, CA","industry":"Financial Technology","skills_json":json.dumps(["Python","PyTorch","Kubernetes","MLOps","Distributed Systems","LLMs"]),"topics_json":json.dumps(["MLOps","LLMs","Platform Engineering","Open Source"]),"experience_json":json.dumps([{"title":"ML Platform Lead","company":"Stripe","duration":"2022–Present","is_current":True},{"title":"Research Engineer","company":"Google Brain","duration":"2018–2022"}]),"posts_json":json.dumps([{"text":"Just open-sourced our ML training pipeline — 3x faster distributed training!","likes":340},{"text":"Why MLOps is the most underrated skill in AI teams right now.","likes":218}]),"status":"analyzed","scraped_at":now_iso()},
    {"url":"https://linkedin.com/in/james-okafor-ai","name":"James Okafor","headline":"AI Research Scientist @ DeepMind | NLP & Reasoning","company":"DeepMind","title":"AI Research Scientist","location":"London, UK","industry":"Artificial Intelligence","skills_json":json.dumps(["Python","JAX","NLP","Transformers","Research","Mathematics"]),"topics_json":json.dumps(["NLP","Reasoning","AI Safety","Research"]),"experience_json":json.dumps([{"title":"Research Scientist","company":"DeepMind","duration":"2021–Present","is_current":True}]),"posts_json":json.dumps([{"text":"Our new paper on chain-of-thought reasoning just dropped on arXiv!","likes":512}]),"status":"approved","scraped_at":now_iso()},
    {"url":"https://linkedin.com/in/priya-sharma-cto","name":"Priya Sharma","headline":"CTO @ Synthesia | Building AI Video at Scale","company":"Synthesia","title":"CTO","location":"London, UK","industry":"Technology","skills_json":json.dumps(["Python","Go","AWS","System Design","Leadership","AI","Video AI"]),"topics_json":json.dumps(["Startup","Leadership","AI Video","Scaling Engineering"]),"experience_json":json.dumps([{"title":"CTO","company":"Synthesia","duration":"2020–Present","is_current":True},{"title":"Staff Engineer","company":"Spotify","duration":"2017–2020"}]),"posts_json":json.dumps([{"text":"Lessons learned scaling our AI video pipeline from 0 to 10M users.","likes":890}]),"status":"analyzed","scraped_at":now_iso()},
    {"url":"https://linkedin.com/in/alex-rivera-devrel","name":"Alex Rivera","headline":"Developer Advocate @ HuggingFace | Open Source ML","company":"HuggingFace","title":"Developer Advocate","location":"Remote","industry":"Open Source / AI","skills_json":json.dumps(["Python","Transformers","Diffusers","Community","Technical Writing","LLMs"]),"topics_json":json.dumps(["Open Source","HuggingFace","Diffusion Models","Community"]),"experience_json":json.dumps([{"title":"Developer Advocate","company":"HuggingFace","duration":"2022–Present","is_current":True}]),"posts_json":json.dumps([{"text":"Just released a beginner guide to fine-tuning Llama 3 — 50k views!","likes":1200}]),"status":"skipped","scraped_at":now_iso()},
    {"url":"https://linkedin.com/in/nina-volkov-data","name":"Nina Volkov","headline":"Head of Data Science @ Revolut | Risk & ML","company":"Revolut","title":"Head of Data Science","location":"Dublin, IE","industry":"FinTech","skills_json":json.dumps(["Python","Scala","Spark","Risk ML","A/B Testing","Feature Stores"]),"topics_json":json.dumps(["FinTech","Risk ML","Data Engineering","Leadership"]),"experience_json":json.dumps([{"title":"Head of Data Science","company":"Revolut","duration":"2021–Present","is_current":True}]),"posts_json":json.dumps([{"text":"How we built a real-time fraud detection system handling 500k txns/sec.","likes":445}]),"status":"approved","scraped_at":now_iso()},
]

analyses = [
    {"profile_id":1,"summary":"Sarah is a top-tier ML infrastructure engineer who bridges research and production. Her open-source contributions and Google Brain background make her an exceptional networking target for anyone in the MLOps space.","interests_json":json.dumps(["Distributed ML","Open Source","MLOps"]),"networking_score":9.2,"score_rationale":"Highly active, strong technical credibility, relevant expertise overlap.","starters_json":json.dumps(["I saw your open-source training pipeline post — what was the biggest engineering challenge?","How do you approach ML platform design for multi-team orgs at Stripe?"]),"connection_note":"Hi Sarah, your open-source ML pipeline work at Stripe is impressive. I'm building similar infra and would love to connect and swap notes!","followup_json":json.dumps(["Great to connect Sarah! Would love to hear about your MLOps lessons at scale."]),"questions_json":json.dumps(["What's your take on the future of ML platforms in the LLM era?"]),"ai_model":"gpt-4o-mini","ai_tokens_used":512,"analyzed_at":now_iso()},
    {"profile_id":2,"summary":"James is a world-class NLP researcher at DeepMind with a focus on reasoning and AI safety. His recent chain-of-thought paper is highly cited and shows exceptional depth.","interests_json":json.dumps(["NLP","AI Safety","Reasoning"]),"networking_score":8.7,"score_rationale":"Deep technical expertise, active researcher, publishing impactful work.","starters_json":json.dumps(["Your chain-of-thought paper is fascinating — how do you evaluate emergent reasoning?","What's your perspective on AI safety in the context of LLM reasoning?"]),"connection_note":"Hi James, your work on reasoning in LLMs is exactly what I've been following. Would love to connect with someone at the frontier of this!","followup_json":json.dumps(["Great to connect! Your CoT paper raised so many interesting questions about emergent reasoning."]),"questions_json":json.dumps(["What evaluation benchmarks do you trust most for reasoning tasks?"]),"ai_model":"gpt-4o-mini","ai_tokens_used":498,"analyzed_at":now_iso()},
    {"profile_id":3,"summary":"Priya is a technical CTO who scaled Synthesia's AI video platform to millions of users. Her blend of engineering depth and leadership makes her a valuable connection for anyone building at scale.","interests_json":json.dumps(["Startup Scaling","AI Video","Engineering Leadership"]),"networking_score":8.1,"score_rationale":"C-level credibility, impressive scaling story, active thought leader.","starters_json":json.dumps(["What was the hardest engineering decision scaling to 10M users at Synthesia?","How do you balance research velocity with production reliability as CTO?"]),"connection_note":"Hi Priya, your journey scaling Synthesia's AI video pipeline is inspiring. As someone building AI products at scale, I'd love to connect!","followup_json":json.dumps(["Wonderful to connect Priya! Your scaling post was really insightful."]),"questions_json":json.dumps(["How do you think about hiring for a senior engineering org?"]),"ai_model":"gpt-4o-mini","ai_tokens_used":476,"analyzed_at":now_iso()},
    {"profile_id":4,"summary":"Alex is the go-to DevRel voice at HuggingFace, producing high-impact educational content that reaches hundreds of thousands of ML practitioners. A great connector in the open-source AI community.","interests_json":json.dumps(["Open Source","Community Building","LLMs"]),"networking_score":7.4,"score_rationale":"High reach and influence in the OSS ML community, but less direct technical overlap.","starters_json":json.dumps(["Your Llama 3 fine-tuning guide was exactly what I needed — any plans for a follow-up?"]),"connection_note":"Hi Alex, your HuggingFace tutorials have helped me immensely. Would love to connect with someone making ML accessible!","followup_json":json.dumps(["Thanks for connecting Alex! Your content is top-notch."]),"questions_json":json.dumps(["What models are you most excited about in the open-source space right now?"]),"ai_model":"gpt-4o-mini","ai_tokens_used":423,"analyzed_at":now_iso()},
    {"profile_id":5,"summary":"Nina leads data science at Revolut tackling real-time fraud at massive scale. Her engineering depth in risk ML and feature stores is rare and highly valuable.","interests_json":json.dumps(["Risk ML","FinTech","Real-time Systems"]),"networking_score":8.4,"score_rationale":"Rare combination of ML depth and production scale in FinTech risk systems.","starters_json":json.dumps(["Your fraud detection system post was brilliant — how do you handle concept drift at 500k tps?","What does your feature store architecture look like for real-time inference?"]),"connection_note":"Hi Nina, your real-time fraud detection work at Revolut is incredibly impressive. I'm working on similar challenges and would love to connect!","followup_json":json.dumps(["So good to connect Nina! Your Revolut fraud system is exactly the kind of scale I'm curious about."]),"questions_json":json.dumps(["How do you manage model monitoring in a high-velocity transaction environment?"]),"ai_model":"gpt-4o-mini","ai_tokens_used":489,"analyzed_at":now_iso()},
]

# Insert profiles
pids = [db.upsert_profile(p) for p in profiles]
print(f"✓ Inserted {len(pids)} profiles")

# Fix profile_ids to match actual DB ids
for i, analysis in enumerate(analyses):
    analysis["profile_id"] = pids[i]
    db.save_analysis(analysis)
    db.update_profile_status(pids[i], profiles[i]["status"])

print(f"✓ Inserted {len(analyses)} analyses")
print("Demo data seeded successfully!")
